services:
  # HDFS
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
    networks:
      - data-pipeline-net
    mem_limit: 512m

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - ./hadoop/datanode:/hadoop/dfs/data
    ports:
      - "9864:9864"
    networks:
      - data-pipeline-net
    mem_limit: 1g

  # Spark Master
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - data-pipeline-net
    mem_limit: 512m

  # Spark Worker (only one to save RAM)
  spark-worker:
    image: bitnami/spark:3.4.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1g
    ports:
      - "8081:8081"
    networks:
      - data-pipeline-net
    mem_limit: 1.5g

  # Airflow (combine webserver + scheduler)
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
      - AIRFLOW_CONN_HDFS_DEFAULT=hdfs://namenode:9000
      - SPARK_HOME=/opt/spark
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./jobs:/opt/spark/app
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "8082:8080"
    command: bash -c "airflow db init && airflow webserver & airflow scheduler"
    networks:
      - data-pipeline-net
    mem_limit: 1g

  # Elasticsearch (already capped at 512m)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
    networks:
      - data-pipeline-net
    mem_limit: 512m

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - data-pipeline-net
    mem_limit: 256m

networks:
  data-pipeline-net:
    driver: bridge
